title: Henrik Leifsson # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br> 
  <a href="https://hvleifsson.github.io/printing">3D-Printing</a>   
  <br><br>
  <a href="https://hvleifsson.github.io/about">About</a> 
  <br><br>
  <a href="https://hvleifsson.github.io/contact">Contact</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/hvleifsson/">LinkedIn</a> 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
